### ISSUE TITLE
Add vopros.me to default blacklist

### ISSUE THREAD

**Issue by ezhlobo** [ezhlobo/vkleaner#22]
I think that "vopros.me" should be added to default blacklist.

What do you think, @proghat?

**Comment by dzhlobo** [comment]
:). Agree.

2013/2/14 Evgeny Zhlobo notifications@github.com

**Comment by ezhlobo** [comment]
I'll add some sites: sprashivai.by, vopros.me, voprosmne.ru, sprashivalka.com, askbook.me, my-truth.ru.
