### ISSUE TITLE
extension hides some post with pictures from communities.

### ISSUE THREAD

**Issue by yoihito** [ezhlobo/vkleaner#38]
It hides some post and some posts leaves without any changes.

**Comment by ezhlobo** [comment]
Can you show me screenshot?

**Comment by yoihito** [comment]
![2014-01-18 0 50 38](https://f.cloud.github.com/assets/1703018/1944831/99034462-7fc1-11e3-8ac8-21d51e7fe06e.png)
here

**Comment by ezhlobo** [comment]
Vkleaner detected this post as post via some application. Try to switch off hiding posts via apps in vkleaner settings.

**Comment by ezhlobo** [comment]
Continue in #40
