### ISSUE TITLE
Need to unblock apps

### ISSUE THREAD

**Issue by ezhlobo** [ezhlobo/vkleaner#40]
Now vk.com publish posts via web, desktop and mobile apps (which uses vk API) as some vk's application. I think stopping to hide posts via apps.

**Comment by dzhlobo** [comment]
I think you should make whitelist of such applications and add to it only official clients.

**Comment by ezhlobo** [comment]
@Proghat, now vkleaner works so. But instagram which sharing posts to vk isn't official. Kate Mobile is popular mobile app but it's not official.

**Comment by dzhlobo** [comment]
@ezhlobo, maybe you should also add well known apps too. But I don't want to view posts by games or apps which share fun images.

**Comment by ezhlobo** [comment]
@Proghat, thank you.

**Comment by ezhlobo** [comment]
If you know some apps, welcome to #41.
