### ISSUE TITLE
Visible message when options saved

### ISSUE THREAD

**Issue by dzhlobo** [ezhlobo/vkleaner#6]
I think mesasge after saving options should be more visible. Not only few second on button.

**Comment by dzhlobo** [comment]
I think alert should be visible more than 600 ms.

**Comment by ezhlobo** [comment]
What value should I set?

**Comment by dzhlobo** [comment]
I think it should be not less than 1.5-2 sec.

**Comment by ezhlobo** [comment]
Fix in new interface
